final-web/src/main/java/com/tfj/beta/model/Product.java
package com.tfj.beta.model;

import java.sql.SQLException;
import java.util.List;

import org.apache.commons.lang3.StringUtils;

import com.jfinal.ext.plugin.tablebind.TableBind;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.IAtom;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.Page;

@TableBind(tableName = "t_product", pkName = "id")
public class Product extends Model<Product> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9082359035209547829L;
	
	public static final Product dao = new Product();
	public static final ProductValue productValueDao = new ProductValue();
	public static final ProductResult productResultDao = new ProductResult();
	public static final String ID = "id";
	public static final String PRODUCT_NAME = "product_name";
	public static final String CATEGORY_ID = "category_id";
	public static final String CATEGORY_NAME = "category_name";
	public static final String PLANT_TYPE = "plant_type";
	public static final String PRODUCT_LEVEL = "product_level";
	public static final String PRODUCT_YEAR = "product_year";
	public static final String PLANTBASE_ID = "plantbase_id";
	public static final String PLANTBASE_NAME = "plantbase_name";
	public static final String OPERATOR = "operator";
	public static final String AUDITFLAG = "auditflag";
	public static final String AUDITORID = "auditorid";
	public static final String AUDITOR = "auditor";
	public static final String AUDIT_TIME = "audit_time";
	public static final String REMARK="remark";
	public static final String DICTYPE="PLANTTYPE";//数字字典种植方式
	public static final String DICTYPE_DJ="Product_Rank";//数字字典等级方式
	
	public String getAuditflagName() {
		Integer auditFlag = getInt(AUDITFLAG);
		if (auditFlag != null) {
			return AuditState.getName(auditFlag);
		}
		return AuditState.UNAUDITED.getName();
	}
	
	public List<Product> getProductList() {

		StringBuffer stringBuffer = new StringBuffer("SELECT * FROM `t_product` where auditflag = 1");
		
		return this.find(stringBuffer.toString());
	}
	
	public Page<Product> searchPaginate(int pageNumber, int pageSize,
			Product product, String orderby,List<Unit> units,String admin) {
		String select = "SELECT * ";
		StringBuffer stringBuffer = new StringBuffer(
				"FROM t_product WHERE 1=1 ");
		if (null != product.getStr(PRODUCT_NAME) && !"".equals(product.getStr(PRODUCT_NAME))) {
			stringBuffer.append("AND ").append(PRODUCT_NAME).append(" like '%")
					.append(product.getStr(PRODUCT_NAME).trim().equals("'")?"''":product.getStr(PRODUCT_NAME).trim()).append("%' "); // 用户名向后模糊查找
		}

		if (null != product.getLong(CATEGORY_ID) && -1 != product.getLong(CATEGORY_ID)) {
			stringBuffer.append(" AND ").append(CATEGORY_ID).append("=").append(product.getLong(CATEGORY_ID));
		}

		
		if (null != product.getInt(AUDITFLAG) && -1 != product.getInt(AUDITFLAG)) {
			stringBuffer.append(" AND ").append(AUDITFLAG).append("=").append(product.getInt(AUDITFLAG)); 
		}
		if(!"true".equals(admin)){
			String str=null;//获取所有unitId  组成字符串
			StringBuffer sb=new StringBuffer();
			if(units.size()>0){
				for(Unit unit:units){
					sb.append(unit.getLong(Unit.ID)+",");
				}
				int endIndex=sb.toString().lastIndexOf(",");
				str=sb.toString().substring(0, endIndex);
			}
			stringBuffer.append(" AND unit_id in(")
			.append(str)
			.append(")");
		}
		
		if (StringUtils.isNotBlank(orderby)) {
			stringBuffer.append(" order by " + orderby);
		} else {
			stringBuffer.append(" order by id desc");
		}
		return paginate(pageNumber, pageSize, select, stringBuffer.toString());
	}
	
	public boolean deleteByIds(String[] ids) {
		StringBuffer stringBuffer = new StringBuffer(
				"delete from `t_product` where ");
		if (null != ids && 1 == ids.length) {
			stringBuffer.append("id = ?");
			return 0 == Db.update(stringBuffer.toString(), ids[0]) ? false
					: true;
		} else if (null != ids && ids.length > 1) {
			stringBuffer.append("id in('");
			for (String id : ids) {
				stringBuffer.append(id).append("','");
			}
			stringBuffer.delete(stringBuffer.length() - 2,
					stringBuffer.length()); // 去掉最后一个,和'
			stringBuffer.append(")");
			return 0 == Db.update(stringBuffer.toString()) ? false : true;
		}
		return false;
	}
	
	public boolean queryAssociatedById(String id) {
		boolean isFlag=false;
		Product product=this.findFirst("SELECT * FROM t_product WHERE id="+id);
		if(product.getInt(Product.AUDITFLAG)!=null&&product.getInt(Product.AUDITFLAG)!=0){//值为未审核时，不管是否有关联，都删除（ ）
			String sql="SELECT * from t_product,t_product_result where t_product_result.product_id="+id+" LIMIT 1";
			if(this.findFirst(sql)==null){
				sql="SELECT * from t_product,t_product_value where t_product_value.product_id="+id+" LIMIT 1";
			}
			if(this.findFirst(sql)!=null){
				isFlag=true;
			}
			//return this.findFirst(sql)==null?false:true;
		}
		return isFlag;
	}

	/**
	 * 强制删除
	 * @param id
	 * @return
	 * @throws SQLException 
	 */
	public boolean mandatoryDeleteByIds(final String id){
		//Product product = this.findById(id);
		final String tpsql="DELETE from t_product WHERE id=?";
		final String pvsql="DELETE from t_product_result WHERE product_id=?";
		final String prql="DELETE from t_product_value WHERE product_id=?";
		//final String casql="UPDATE t_category SET nums=nums-1 where id="+product.getLong(Product.CATEGORY_ID);
		//final String icsql="UPDATE t_index_count SET count_categoryrecord=count_categoryrecord-1";
		return Db.tx(new IAtom(){//事物处理
			public boolean run() throws SQLException {
			int tp=Db.update(tpsql,id);	
			int tv=Db.update(pvsql,id);
			int pr=Db.update(prql,id);	
			//int ca=Db.update(casql);
			//int ic=Db.update(icsql);
			return (/*ic > 0 && ca > 0 && */tp > 0) || tv > 0 || pr > 0;
		}});
	}
	public void finishInit(final Long product_id) {
		Db.update("UPDATE t_product SET remark='1' where id="+product_id);
	}

	public boolean releaseAudit(final Product product) {
		int all=0;
		List<ProductValue> pvs=productValueDao.getProductValuesByProductId(product.getLong(Product.ID));
		
		for(ProductValue pv:pvs){//统计插入条数
			all=all+1;
		}
		final int result=all;
		final String prsql="UPDATE t_product SET auditflag=0  WHERE id=?";
		final String pvql="UPDATE t_product_value SET auditflag=0 WHERE product_id=?";
		return Db.tx(new IAtom(){//事物处理
			public boolean run() throws SQLException {
			int pr=Db.update(prsql,product.getLong(Product.ID));
			int pv=Db.update(pvql,product.getLong(Product.ID));
			return pr > 0 && pv == result;
		}});
	}
	
	/**
	 * 产品删除
	 * @param product
	 * @return
	 */
	public boolean deleteProduct(final Product product) {
		int pvall=0;//产品值条数初始化为0
		int psall=0;//产品二维码表初始化为0
		List<ProductValue> pvs=productValueDao.getProductValuesByProductId(product.getLong(Product.ID));
		ProductResult productResult=productResultDao.getProductResultByProductId(String.valueOf(product.getLong(Product.ID)));
		
		for(ProductValue pv:pvs){//统计插入条数
			pvall=pvall+1;
		}
		if(productResult!=null){
			psall=1;
		}
		final int pvresult=pvall;//产品值总条数
		final int psresult=psall;//产品值总条数
		final String pvsql="DELETE FROM t_product_value WHERE product_id=?";
		final String prql="DELETE FROM t_product WHERE id=?";
		final String psql="DELETE FROM t_product_result WHERE product_id=?";
		//更新种类的产品数量
		final String casql="UPDATE t_category SET nums=nums-1 where id="+product.getLong(Product.CATEGORY_ID);
		final String icsql="UPDATE t_index_count SET count_categoryrecord=count_categoryrecord-1";
		return Db.tx(new IAtom(){//事物处理
			public boolean run() throws SQLException {
			int pv=Db.update(pvsql,product.getLong(Product.ID));
			int pr=Db.update(prql,product.getLong(Product.ID));	
			int ps=Db.update(psql,product.getLong(Product.ID));	
			int ca=Db.update(casql);
			int ic=Db.update(icsql);
			return pr > 0 && pv == pvresult && ps==psresult&&ca>0 &&ic > 0;
		}});
	}
	/**
	 * 根据种类ID查找所以的产品
	 * @param categoryId
	 * @return
	 */
	public List<Product> getProductsByCategoryId(String categoryId){
		return this.find("SELECT * FROM t_product WHERE category_id="+categoryId);
	}
	
	public Boolean updateProductAddNum(){
		String sql = "UPDATE t_index_count SET count_categoryrecord=count_categoryrecord+1";
		return 0==Db.update(sql)?false:true;
	}
	
}

final-web/src/main/webapp/WEB-INF/pages/admin/productValue/newUploadDemo.jsp
<#include "../common/layout/__mainlayout.jsp">
<#include "../common/__pagination.jsp">

<#assign pageCss>
<style>
	body{font-size: 12px;}
	body,p,div{ padding: 0; margin: 0;}
	.wraper{ padding: 30px 0;}
	.btn-wraper{ text-align: center;}
	.btn-wraper input{ margin: 0 10px;}
	#file-list{ width: 350px; margin: 20px auto;}
	#file-list li{ margin-bottom: 10px;}
	.file-name{ line-height: 30px;}
	.progress{ height: 4px; font-size: 0; line-height: 4px; background: orange; width: 0;}
	.tip1{text-align: center; font-size:14px; padding-top:10px;}
    .tip2{text-align: center; font-size:12px; padding-top:10px; color:#b00}
</style>
</#assign>

<#assign pageJavascript>
	<script src="${contextPath}/static/admin/pv/plupload/js/plupload.full.js"></script>
	<script type="text/javascript">
	$(document).ready(function(){
		var uploader = new plupload.Uploader({ //实例化一个plupload上传对象
			browse_button : 'browse',
			url : '${contextPath}/admin/productValue/uploadDemo',
			flash_swf_url : '${contextPath}/static/admin/pv/plupload/js/plupload.flash.swf',
			silverlight_xap_url : '${contextPath}/static/admin/pv/plupload/js/plupload.silverlight.xap',
			multi_selection : false,
		});
		uploader.init(); //初始化

		//绑定文件添加进队列事件
		uploader.bind('FilesAdded',function(uploader, files){
			// allPrpos(uploader.total);
			console.log("File Size: >>>" + uploader.total.queued);
			
			var file_name = files[0].name; //文件名
			//构造html来更新UI
			var html = '<li id="file-' + files[0].id +'"><p class="file-name">' + file_name + '</p><p class="progress"></p></li>';
			$('#file-list').html(html);
			
			
			 $.each(uploader.files, function (i, file) {
				 if (uploader.files.length <= 1) {
					 return;
			     }
				 uploader.removeFile(file);
			 });
		});
		 
		//绑定文件上传进度事件
		uploader.bind('UploadProgress',function(uploader,file){
			$('#file-'+file.id+' .progress').css('width',file.percent + '%');//控制进度条
		});

		//上传按钮
		$('#upload-btn').click(function(){
			uploader.start(); //开始上传
		});
		
		function allPrpos ( obj ) { 
			  // 用来保存所有的属性名称和值 
			  var props = "" ; 
			  // 开始遍历 
			  for ( var p in obj ){ // 方法 
			  if ( typeof ( obj [ p ]) == " function " ){ obj [ p ]() ; 
			  } else { // p 为属性名称，obj[p]为对应属性的值 
			  props += p + " = " + obj [ p ] + " /t " ; 
			  } } // 最后显示所有的属性 
			  console.log( props ) ;
		}
	});
	</script>
</#assign>

<@mainlayout pageBreadCrumbs=pageBreadCrumbs pageCss=pageCss pageJavascript=pageJavascript currentMenu="userRoleFlag-productValueFlag">
	<p class="tip2">注意：该demo把上传的地址设为了一个静态的html页面，所以文件并不会真正的上传到服务器，但这不会影响上传功能的演示！</p>
	<div class="wraper">
		<div class="btn-wraper">
			<input type="button" value="选择文件..." id="browse" />
			<input type="button" value="开始上传" id="upload-btn" />
		</div>
		<ul id="file-list">

		</ul>
	</div>
</@mainlayout>

final-web/src/main/webapp/WEB-INF/pages/admin/productValue/plantInput.jsp
<div class="col-xs-8 col-sm-8 widget-color-green">
	<div class="wrap widget-header widget-header-small">
		<#if (product.auditflag?? && product.auditflag != 2)>
		<@shiro.hasPermission name="product_admin_plantAudit">
		<button type="button" name="auditProductValue" class="btn btn-sm btn-success"><i class="ace-icon fa fa-check"></i>审核</button>
		</@shiro.hasPermission>   
		<button type="button" name="saveProductValue" class="btn btn-sm btn-success"><i class="ace-icon fa fa-check"></i>保存</button>
		<#else><!-- 为了释放值所用-->
		<@shiro.hasPermission name="product_admin_plantAudit">
		<button style="display: none;" type="button" name="auditProductValue" class="btn btn-sm btn-success plantInputAudit"><i class="ace-icon fa fa-check"></i>审核</button>
		</@shiro.hasPermission>   
		<button style="display: none;" type="button" name="saveProductValue" class="btn btn-sm btn-success plantInputSave"><i class="ace-icon fa fa-check"></i>保存</button>
		
		</#if>
	</div>
	
	
	<div id="PlantContainer" class="container borderStyle">
	</div>
</div>

final-web/src/main/webapp/WEB-INF/pages/admin/productValue/productValueTab.jsp
<#include "../common/layout/__mainlayout.jsp">
<#include "../common/__pagination.jsp">

<#assign pageCss>
<link rel="stylesheet" href="${contextPath}/static/admin/assets/css/chosen.css" />
<link rel="stylesheet" href="${contextPath}/static/admin/assets/css/datepicker.css">
<link rel="stylesheet" href="${contextPath}/static/admin/assets/css/jquery-ui.custom.css" />
<link rel="stylesheet" href="${contextPath}/static/admin/pv/css/allLink.css" type="text/css">
<link rel="stylesheet" href="${contextPath}/static/admin/pv/css/public.css" type="text/css">
<link rel="stylesheet" href="${contextPath}/static/admin/assets/css/zTreeStyle/zTreeStyle.css" type="text/css">
</#assign>

<#assign pageBreadCrumbs>
<li>产品管理</li>
<li class="active">产品数据录入</li>
</#assign> 

<#assign pageJavascript>
    <script src="${contextPath}/static/admin/assets/js/fileupload/ajaxfileupload.js"></script>
    <script src="${contextPath}/static/admin/assets/js/jquery.ztree.all-3.5.min.js"></script>
	<script src="${contextPath}/static/admin/pv/js/allLink.js"></script>
	<script type="text/javascript">
	var P1_NAME = "PLANT_PROCESS";
	var P2_NAME = "SUPERVISE_PROCESS";
	var P3_NAME = "WAREHOUSE_PROCESS";
	var P4_NAME = "SALE_PROCESS";
	
	var P1_Container = "PlantContainer";
	var P2_Container = "SuperviseContainer";
	var P3_Container = "WarehouseContainer";
	var P4_Container = "SaleContainer";
	
	var l_proces_type = '${Locate_Process_Type}';
	var l_template_name = '${Locate_Template_Name}';
	var Image_Pattern = '${Image_Pattern}';
	
	var orgWidgets;
	var inited;
	
			$(document).ready(function(){
				
				
				window.tfj_Full_ContextPath = '${Full_Context_Path}';
				window.tfj_ContextPath = '${contextPath}';
				window.tfj_pv_ProcessType = P1_NAME;
				window.tfj_pv_Container = P1_Container;
				
	            // 清除远程modal数据
	            $("#editModal").on("hidden.bs.modal", function(){
	                $(this).removeData("bs.modal");
	            });
				
				//初始化页面 tab不允许 点击 
				$("#plantProcessMenu").attr("href", "#plantProcess");
				$("#superviseMenu").attr("href", "#superviseProcess");
				$("#wareHouseMenu").attr("href", "#wareHouseProcess");
				$("#saleMenu").attr("href","#saleProcess");
				
				// 种植环节 
				$("#plantProcessMenu").bind("click", function(){
					 var category_id = ${session["category_id"]};
					 loadPageData(P1_NAME, P1_Container, "plantTree", category_id);
				});
				
				// 加工环节 
				$("#superviseMenu").bind("click", function(event){
					var category_id = ${session["category_id"]};
					loadPageData(P2_NAME, P2_Container, "superviseTree", category_id);
					
				});
				
				// 仓管流通环节 
				$("#wareHouseMenu").bind("click", function(){
					var category_id = ${session["category_id"]};
					loadPageData(P3_NAME, P3_Container, "wareHouseTree", category_id);
				});
				
				// 销售环节 
				$("#saleMenu").bind("click", function(){
					var category_id = ${session["category_id"]};
					loadPageData(P4_NAME, P4_Container, "saleTree", category_id);
				});
				
				jQuery(function($){
					$('.dd-handle a').on('mousedown', function(e){
						// e.stopPropagation();
					});
					
					$('[data-rel="tooltip"]').tooltip();
				});
				
				//var l_proces_type = '${Locate_Process_Type}';
				//var l_template_name = '${Locate_Template_Name}';
				reflushTree(l_proces_type);
	        });
	</script>
</#assign>


<@mainlayout pageBreadCrumbs=pageBreadCrumbs pageCss=pageCss pageJavascript=pageJavascript currentMenu="userRoleFlag-productValueFlag">
             <input type="hidden" class="pv_product_id" value="${product.id!}"/>
             <input type="hidden" class="pv_category_id" value="${product.category_id!}"/>
             <table id="contentTable" class="table table-striped table-bordered">
                <thead>
                <tr>
                	<!-- 
                    <th width="40" align="right" >ID</th>
                     -->
                    <th width="150" align="left" style="text-align: center;">名称</th>
                    <th width="150" align="left" style="text-align: center;">种类名称</th>
                    <th width="150" align="left" style="text-align: center;">种植方式</th>
                    <th width="150" align="left" style="text-align: center;">等级</th>
                    <th width="150" align="left" style="text-align: center;">年份</th>
                    <th width="150" align="left" style="text-align: center;">基地</th>
                    <th width="150" align="left" style="text-align: center;">审核状态</th>
                    <#if session['adminType'] == 'true'>
                    <th width="200" align="center" style="text-align: center;">操作</th>
                    </#if>
                </tr>
                </thead>

                <tbody>
                    <tr>
                        <td>${product.product_name!}</td>
                        <td>${product.category_name!}</td>
                        <td>${product.plant_type!}</td>
                        <td>${product.product_level!}</td>
                        <td>${product.product_year!}</td>
                        <td>${product.plantbase_name!}</td>
                        <td id="product_auditflagName">
                        	${product.auditflagName!}
                        </td>
                        <#if session['adminType'] == 'true'>
                        <td align="center">
                        <input type="hidden" class="product_auditflag" value="${product.auditflag!}"/>
                      	
	                        <#if (product.auditflag?? && product.auditflag = 1)>
	                        	<a style="size: 10px;" class="btn btn-sm btn-primary red tooltip-success" href="#" name="CheckProductValue" onclick="finishEntry(${product.id!}, ${product.auditflag!})"  data-rel="tooltip" ><font style="font-weight:bold;">√</font>&nbsp;完成</a>
	                        <#else><!-- 为了释放值所用，注意 finishEntry(id, auditflag) 中参数auditflag 为 1 -->
	                            <a style="display: none;" class="btn btn-sm btn-primary red tooltip-success finish" href="#" name="CheckProductValue" onclick="finishEntry(${product.id!}, 1)"  data-rel="tooltip" ><font style="font-weight:bold;">√</font>&nbsp;完成</a>
	                        </#if>
                        </td>
                        </#if>
                    </tr>
                </tbody>
            </table>

<div class="row">
	<div class="col-xs-12">
		<div >
			<div >
				<div class="tabbable">
					<ul class="nav nav-tabs padding-18">
						<li class="active">
							<a data-toggle="tab" href="#plantProcess" id="plantProcessMenu"> <i class="green ace-icon fa fa-leaf bigger-120"></i> 种植环节</a>
						</li>

						<li>
							<a data-toggle="tab" href="#superviseProcess" id="superviseMenu"> <i class="orange ace-icon fa fa-rss bigger-120"></i> 加工环节</a>
						</li>

						<li>
							<a data-toggle="tab" href="#wareHouseProcess" id="wareHouseMenu"> <i class="blue ace-icon fa fa-users bigger-120"></i> 流通环节</a>
						</li>

						<li>
							<a data-toggle="tab" href="#saleProcess" id="saleMenu"> <i class="pink ace-icon fa fa-picture-o bigger-120"></i> 销售环节</a></li>
					</ul>

					<div class="tab-content no-border padding-24">

						<div id="plantProcess" class="tab-pane tab-pane in active">
							<div>	
								<div class="col-xs-4 col-sm-4">
								     <div class="widget-box widget-color-blue2">
								         <div class="widget-header widget-header-small">
								             <h4 class="widget-title lighter smaller">种植环节</h4>
								         </div>
								
								         <div class="widget-body">
								             <div class="widget-main padding-8">
								                 <ul id="plantTree" class="ztree"></ul>
								             </div>
								         </div>
								     </div>
								     <!--
								     <button type="button" name="release" class="btn btn-sm btn-success"><i class="ace-icon fa fa-check"></i>释放</button>
								       -->
								</div>
								
								<#include "./plantInput.jsp">
							</div>
						</div>

						<div id="superviseProcess" class="tab-pane">
							<div>	
								<div class="col-xs-4 col-sm-4">
								     <div class="widget-box widget-color-blue2">
								         <div class="widget-header widget-header-small">
								             <h4 class="widget-title lighter smaller">加工环节</h4>
								         </div>
								
								         <div class="widget-body">
								             <div class="widget-main padding-8">
								                 <ul id="superviseTree" class="ztree"></ul>
								             </div>
								         </div>
								     </div>
								</div>
								<#include "./superviseInput.jsp">
							
							</div>
						</div>

						<div id="wareHouseProcess" class="tab-pane">
							<div>	
								<div class="col-xs-4 col-sm-4">
								     <div class="widget-box widget-color-blue2">
								         <div class="widget-header widget-header-small">
								             <h4 class="widget-title lighter smaller">流通环节</h4>
								         </div>
								
								         <div class="widget-body">
								             <div class="widget-main padding-8">
								                 <ul id="wareHouseTree" class="ztree"></ul>
								             </div>
								         </div>
								     </div>
								</div>
								
								<#include "./warehouseInput.jsp">
							</div>
						</div>

						<div id="saleProcess" class="tab-pane">
							<div>	
								<div class="col-xs-4 col-sm-4">
								     <div class="widget-box widget-color-blue2">
								         <div class="widget-header widget-header-small">
								             <h4 class="widget-title lighter smaller">销售环节</h4>
								         </div>
								
								         <div class="widget-body">
								             <div class="widget-main padding-8">
								                 <ul id="saleTree" class="ztree"></ul>
								             </div>
								         </div>
								     </div>
								</div>
							<#include "./saleInput.jsp">
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- PAGE CONTENT ENDS -->
	</div>
</div>

<div id="editModal" class="modal fade" style="overflow-y:hidden;">
  <div class="modal-dialog">
    <div class="modal-content"></div>
  </div>
</div>

<p>
  <span style="background-color: #fafafa;"><!-- 右键菜单div -->
    <div id="rMenu" style="position:absolute; display:none;">
	  <li>
	    <ul id="m_add" onclick="addPrivilege();"><li>增加</li></ul>
		<ul id="m_del" onclick="delPrivilege();"><li>删除</li></ul>
		<ul id="m_del" onclick="editPrivilege();"><li>编辑</li></ul>
		<ul id="m_del" onclick="queryPrivilege();"><li>查看</li></ul>
	  </li>
	</div>
  </span>
</p>

<!-- 动画加载 -->
<div class="loading">
	<img src="${contextPath}/static/admin/assets/img/loading_blue.GIF">
	<span class="textTip"></span>
</div>

</@mainlayout>

final-web/src/main/webapp/WEB-INF/pages/admin/productValue/saleInput.jsp
<div class="col-xs-8 col-sm-8 widget-color-green">
	<div class="wrap widget-header widget-header-small">
		<#if (product.auditflag?? && product.auditflag != 2)>
		<@shiro.hasPermission name="product_admin_saleAudit">
		<button type="button" name="auditProductValue" class="btn btn-sm btn-success"><i class="ace-icon fa fa-check"></i>审核</button>
		</@shiro.hasPermission>   
		<button type="button" name="saveProductValue" class="btn btn-sm btn-success"><i class="ace-icon fa fa-check"></i>保存</button>
		<#else><!-- 为了释放值所用-->
		<@shiro.hasPermission name="product_admin_saleAudit">
		<button style="display: none;" type="button" name="auditProductValue" class="btn btn-sm btn-success saleInputAudit"><i class="ace-icon fa fa-check"></i>审核</button>
		</@shiro.hasPermission>   
		<button style="display: none;" type="button" name="saveProductValue" class="btn btn-sm btn-success saleInputSave"><i class="ace-icon fa fa-check"></i>保存</button>
		</#if>
	</div>
	
	<div id="SaleContainer" class="container borderStyle">
	</div>
</div>

final-web/src/main/webapp/WEB-INF/pages/admin/productValue/superviseInput.jsp
<div class="col-xs-8 col-sm-8 widget-color-green">
	<div class="wrap widget-header widget-header-small">
		<#if (product.auditflag?? && product.auditflag != 2)>
		<@shiro.hasPermission name="product_admin_superviseAudit">
		<button type="button" name="auditProductValue" class="btn btn-sm btn-success"><i class="ace-icon fa fa-check"></i>审核</button>
		 </@shiro.hasPermission>   
		<button type="button" name="saveProductValue" class="btn btn-sm btn-success"><i class="ace-icon fa fa-check"></i>保存</button>
		<#else><!-- 为了释放值所用-->
		<@shiro.hasPermission name="product_admin_superviseAudit">
		<button style="display: none;" type="button" name="auditProductValue" class="btn btn-sm btn-success superviseInputAudit"><i class="ace-icon fa fa-check"></i>审核</button>
		 </@shiro.hasPermission>   
		<button style="display: none;" type="button" name="saveProductValue" class="btn btn-sm btn-success superviseInputSave"><i class="ace-icon fa fa-check"></i>保存</button>
		</#if>
	</div>
	
	<div id="SuperviseContainer" class="container borderStyle">
	</div>
</div>

final-web/src/main/webapp/WEB-INF/pages/admin/productValue/warehouseInput.jsp
<div class="col-xs-8 col-sm-8  widget-color-blue">
	<div class="wrap widget-header widget-header-small">
		<#if (product.auditflag?? && product.auditflag != 2)>
		<@shiro.hasPermission name="product_admin_wareHouseAudit">
		<button type="button" name="auditProductValue" class="btn btn-sm btn-warning"><i class="ace-icon fa fa-check"></i>审核</button>
		</@shiro.hasPermission>   
		<button type="button" name="saveProductValue" class="btn btn-sm btn-warning"><i class="ace-icon fa fa-check"></i>保存</button>
		<#else><!-- 为了释放值所用-->
		<@shiro.hasPermission name="product_admin_wareHouseAudit">
		<button style="display: none;" type="button" name="auditProductValue" class="btn btn-sm btn-warning warehouseInputAudit"><i class="ace-icon fa fa-check"></i>审核</button>
		</@shiro.hasPermission>   
		<button style="display: none;" type="button" name="saveProductValue" class="btn btn-sm btn-warning warehouseInputSave"><i class="ace-icon fa fa-check"></i>保存</button>
		</#if>
	</div>
	
	<div id="WarehouseContainer" class="container borderStyle">
	</div>
</div>